### PR TITLE
configured NgRx store to app

### PR DESCRIPTION
**Pull request by vittal288**

### CODE REVIEW

**Comment by vittal288** [comment]
1St PR

**Comment by duncanhunter** [comment]
Hi

Did you intend to push this to the course repo?

**Comment by vittal288** [comment]
Sorry, I am interested to push into my forked repo.


Thanks & Regards
VITTHAL KAMKAR
9844961561

**Comment by duncanhunter** [comment]
Ok makes sense.

I will close this now.

**Pull request closed without merging**
